name: Test Outputs
on:
  workflow_call:
    inputs:
      test_input:
        type: string
        required: false
        default: "hello"
    outputs:
      test_output:
        value: ${{ jobs.test.outputs.result }}
jobs:
  test:
    runs-on: self-hosted
    outputs:
      result: ${{ steps.echo.outputs.result }}
    steps:
      - id: echo
        run: echo "result=ok" >> $GITHUB_OUTPUT
