name: Test Secrets Only
on:
  workflow_call:
    secrets:
      INTERNAL_PYPI_URL:
        required: true
jobs:
  test:
    runs-on: self-hosted
    steps:
      - run: echo "secret length: $(echo -n '${{ secrets.INTERNAL_PYPI_URL }}' | wc -c)"
